### ISSUE TITLE
Errores básicos

### ISSUE THREAD

**Issue by raquelcedazo** [aigora/twQ103_1920-stars#1]
Hola:

Un par de errores fundamentales que veo en vuestro archivo del menú:
- Los ficheros en C tienen la extensión .c (y no .cpp que corresponde a otro lenguaje C++). 
- Las variables según hemos explicado en clase se declaran justo debajo del main, todas juntas. No declaréis variables en medio del código.

Un saludo.

**Comment by claudiarosales9** [comment]
errores corregidos
